# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 699)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_kb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_kb.setObjectName("pushButton_kb")
        self.verticalLayout.addWidget(self.pushButton_kb)
        self.pushButton_cm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cm.setObjectName("pushButton_cm")
        self.verticalLayout.addWidget(self.pushButton_cm)
        self.pushButton_lcd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_lcd.setObjectName("pushButton_lcd")
        self.verticalLayout.addWidget(self.pushButton_lcd)
        self.pushButton_ts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ts.setObjectName("pushButton_ts")
        self.verticalLayout.addWidget(self.pushButton_ts)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.batButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.batButton.setObjectName("batButton")
        self.verticalLayout.addWidget(self.batButton)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 2, 1)
        self.diskTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.diskTable.setObjectName("diskTable")
        self.diskTable.setColumnCount(0)
        self.diskTable.setRowCount(0)
        self.gridLayout.addWidget(self.diskTable, 4, 2, 1, 1)
        self.userOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.userOutput.setReadOnly(True)
        self.userOutput.setObjectName("userOutput")
        self.gridLayout.addWidget(self.userOutput, 4, 1, 1, 1)
        self.batteryTable = BatWidget(parent=self.centralwidget)
        self.batteryTable.setObjectName("batteryTable")
        self.gridLayout.addWidget(self.batteryTable, 5, 1, 1, 2)
        self.reportButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reportButton.setObjectName("reportButton")
        self.gridLayout.addWidget(self.reportButton, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 10)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 30)
        self.gridLayout.setRowStretch(5, 30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtGui.QAction(parent=MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionConsole = QtGui.QAction(parent=MainWindow)
        self.actionConsole.setObjectName("actionConsole")
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addAction(self.actionConsole)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jochems TestTool"))
        self.pushButton_kb.setText(_translate("MainWindow", "Keyboard"))
        self.pushButton_cm.setText(_translate("MainWindow", "Camera"))
        self.pushButton_lcd.setText(_translate("MainWindow", "LCD"))
        self.pushButton_ts.setText(_translate("MainWindow", "TouchScreen"))
        self.pushButton_2.setText(_translate("MainWindow", "Sound"))
        self.batButton.setText(_translate("MainWindow", "Battery"))
        self.userOutput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.reportButton.setText(_translate("MainWindow", "Maak een raport"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionConsole.setText(_translate("MainWindow", "Console"))
from widgets.BatteryWidget import BatWidget
